version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
      golang: 1.21
    commands:
      - echo "Installing k6 ..."
      - curl -s https://packagecloud.io/install/repositories/loadimpact/k6/script.deb.sh | sudo bash
      - sudo apt-get install k6
      - go install go.k6.io/xk6/cmd/xk6@latest
      - xk6 build --with github.com/kubeshop/xk6-tracetest@latest
      - export K6_BROWSER_ENABLED=true
      - npm ci
      - ls
  build:
    commands:
      - k6 run --out web-dashboard=report=./reports/test-report-dashboard.html run.test.js
      - cd reports
      - ls

artifacts:
  files:
    - reports/testreport.html
    - reports/test-report-dashboard.html
