name: Connect to EC2 Instance

on:
  push:
    branches:
      - main  # Trigger on push to the main branch, modify if needed.

jobs:
  ssh-connect:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up SSH private key
        run: |
          mkdir -p ~/.ssh
          echo "$AWS_SSH_PRIVATE_KEY" > ~/.ssh/bot.pem
          chmod 400 ~/.ssh/bot.pem

      - name: Connect to EC2 instance
        run: |
          INSTANCE_PUBLIC_DNS="ec2-98-84-46-109.compute-1.amazonaws.com"  # Public DNS of your EC2 instance
          # Automatically accept the host key
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/bot.pem ubuntu@$INSTANCE_PUBLIC_DNS "echo 'Connected successfully!'"
        env:
          AWS_SSH_KEY: ${{ secrets.AWS_SSH_KEY }}
